# Generated by Django 3.0.8 on 2020-09-12 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200912_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Marks'),
        ),
    ]
